import {
  ENTITY_TYPES,
  ALLOWED_EXCEL_FILE_TYPES,
  ALLOWED_LESSON_IMAGE_FILE_TYPES,
  ALLOWED_PDF_FILE_TYPES,
  ALLOWED_PRESENTATION_FILE_TYPES,
  ALLOWED_VIDEO_FILE_TYPES,
  ALLOWED_WORD_FILE_TYPES,
  PERMISSIONS,
  RESOURCE_LIBRARY_ASSET_TYPE,
} from "@repo/shared";

import { RESOURCE_RELATIONSHIP_TYPES } from "src/file/file.constants";

import type { ResourceLibraryAssetType } from "./schemas/resource-library.schema";

export const RICH_TEXT_ENTITY_TYPES = [
  ENTITY_TYPES.LESSON,
  ENTITY_TYPES.ARTICLES,
  ENTITY_TYPES.NEWS,
] as const;

export const RICH_TEXT_RELATIONSHIP_TYPES = [
  RESOURCE_RELATIONSHIP_TYPES.ATTACHMENT,
  RESOURCE_RELATIONSHIP_TYPES.CONTENT,
] as const;

export const RICH_TEXT_ASSET_MIME_TYPES_BY_TYPE = {
  [RESOURCE_LIBRARY_ASSET_TYPE.IMAGE]: ALLOWED_LESSON_IMAGE_FILE_TYPES,
  [RESOURCE_LIBRARY_ASSET_TYPE.VIDEO]: ALLOWED_VIDEO_FILE_TYPES,
  [RESOURCE_LIBRARY_ASSET_TYPE.PDF]: ALLOWED_PDF_FILE_TYPES,
  [RESOURCE_LIBRARY_ASSET_TYPE.PRESENTATION]: ALLOWED_PRESENTATION_FILE_TYPES,
  [RESOURCE_LIBRARY_ASSET_TYPE.DOCUMENT]: [...ALLOWED_EXCEL_FILE_TYPES, ...ALLOWED_WORD_FILE_TYPES],
} satisfies Partial<Record<ResourceLibraryAssetType, readonly string[]>>;

export const KNOWN_RICH_TEXT_ASSET_MIME_TYPES = Object.values(
  RICH_TEXT_ASSET_MIME_TYPES_BY_TYPE,
).flat();

export const RESOURCE_LIBRARY_PERMISSIONS = [
  PERMISSIONS.COURSE_UPDATE,
  PERMISSIONS.COURSE_UPDATE_OWN,
  PERMISSIONS.ARTICLE_MANAGE,
  PERMISSIONS.ARTICLE_MANAGE_OWN,
  PERMISSIONS.NEWS_MANAGE,
  PERMISSIONS.NEWS_MANAGE_OWN,
] as const;

export const RESOURCE_FOLDER_COLORS = [
  "neutral",
  "red",
  "orange",
  "yellow",
  "green",
  "blue",
  "purple",
  "pink",
] as const;

export const RESOURCE_FOLDER_DEFAULT_COLOR = "neutral";
